OPENAI_API_KEY = "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"
NAVER_CLIENT_ID = "HofWAtRrLaDr6H1FmNpv"
NAVER_CLIENT_SECRET = "w8H4wOcAqb"
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_PROJECT = "HeartPin_Production"